### ISSUE TITLE
Plugin error - prof_omemo_plugin.prof_on_message_stanza_send(): return value undefined, expected string, unicode or None

### ISSUE THREAD

**Issue by devurandom** [ReneVolution/profanity-omemo-plugin#25] opened 2017-06-23 13:10 UTC
When I type `/omemo start` for an OMEMO enabled contact and then try to write a message to them, I see this in the Profanity main window: `Plugin error - prof_omemo_plugin.prof_on_message_stanza_send(): return value undefined, expected string, unicode or None`.

During the whole time, the session is shown as `unencrypted` in Profanity, and all messages are transmitted unencrypted.

Profanity version is 0.5.1, plugin version is 0.1.1.

Updating to 8e2b0e394431258fdfd034c22af4625d97b6b2f7 solves the issue. Should a new release be cut?

**Comment by ReneVolution** [comment] 2017-06-23 13:22
Just to confirm ... are you using the plugin from master?
What is an "OMEMO enabled contact"? Is that someone who has announced it's device id and bundle?

**Comment by devurandom** [comment] 2017-06-25 12:13
I edited the description, adding the required information, probably after you received the email you replied to:

> > Profanity version is 0.5.1, plugin version is 0.1.1.
> > Updating to 8e2b0e3 solves the issue. Should a new release be cut?
>
> Just to confirm ... are you using the plugin from master?

> What is an "OMEMO enabled contact"? Is that someone who has announced it's device id and bundle?

That is someone who I am already exchanging OMEMO encrypted messages with, by means of Conversations.

**Comment by ReneVolution** [comment] 2017-06-25 13:54
Ok. So, I close this ticket then. A new version will be released soon.

**Closed by ReneVolution** 2017-06-25 13:54 UTC

**Comment by devurandom** [comment] 2017-07-09 17:02
Do you have an ETA for the release?

**Comment by ReneVolution** [comment] 2017-07-09 19:58
There is still a couple of issues i would like to fix first. End of July seems feasible, maybe earlier, no promises.

**Comment by licaon-kter** [comment] 2017-08-23 01:19
Building from master, still seeing this on Termux/profanity 0.5.1.

**Comment by licaon-kter** [comment] 2017-09-24 00:38
So this was fixed?

Still seeing it:
* unencrypted works ok
* switch OMEMO on
* send messages, ok, they're at least sent... but still unencrypted
* log says: https://gist.github.com/licaon-kter/0c2730db7b90210b2feacbc00e712a76

**Comment by ReneVolution** [comment] 2017-09-26 21:42
@licaon-kter The issue is different. For some - yet unknown - reason, it fails for you to create your own bundle announcement message. It is an serialisation issue, which is weird as it works perfectly on other machines. I wonder if this is some string/bytes issue with Python 3.6.

**Comment by licaon-kter** [comment] 2017-09-26 22:42
Maybe it's a Termux (and associated ARM packages) thing?

**Comment by ReneVolution** [comment] 2017-09-28 22:13
Yes. Possible. Can't test that though.
